name: 'Execução manual do teste de controller'

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Baixando o node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      
      - name: Instalando dependências
        run: npm install
      
      - name: Iniciando o servidor
        run: npm run start-rest &
      
      - name: Aguardando a API subir
        run: sleep 5
      
      - name: Rodando os testes de api
        run: npm run test-external